### PR TITLE
resolve dependency version as tag

### LINKED ISSUE #74: ied can't understand "latest" version label
Hey, first of all, congratulations for this project, it is really awesome and clever.

I'm unable to install any dependency with the **latest** version label, you can reproduce this by doing `ied install async@latest`

This was the error I got

```
/usr/local/lib/node_modules/ied/lib/install_cmd.js:65
        if (err) throw err
                       ^
Error: Unknown package spec: tag on async@latest
    at resolve (/usr/local/lib/node_modules/ied/lib/resolve.js:24:8)
    at fn (/usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:746:34)
    at /usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:1213:16
    at /usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:166:37
    at /usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:706:43
    at /usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:167:37
    at Object.async.waterfall (/usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:710:44)
    at install (/usr/local/lib/node_modules/ied/lib/install.js:137:9)
    at /usr/local/lib/node_modules/ied/lib/install_cmd.js:48:9
    at /usr/local/lib/node_modules/ied/node_modules/async/lib/async.js:356:13
```

### PR DESCRIPTION
**Pull request by just-boris**
now `ied install babel-core@latest` is supported

closes #74

### CODE REVIEW

File: test/unit/resolve.js [hunk 1]
```diff
@@ -200,12 +229,5 @@ describe('resolve', function () {
         done()
       })
     })
-
-    it('should throw on unknown version spec', function (done) {
-      resolve('some-package', 'unknown spec', function (err) {
-        assert(err)
-        done()
-      })
-    })
```
Comment (just-boris) [inline test/unit/resolve.js]: Now all other version strings are treated as tags. There is no need to test this case now.

**Comment by alexanderGugel** [comment]
:+1: Awesome!
